### ISSUE TITLE
Null values not very clear

### ISSUE THREAD

**Issue by lightclient** [ethereum/execution-specs#203]
`eth_getTransactionByHash` returns either a transaction (if found), or `null`. It appears to be encoded correctly via OpenRPC, however the way it's displayed isn't very clear. It shows `OneOf` and then the object and then `null`.

![2021-06-01-1622559155_screenshot_2560x1440](https://user-images.githubusercontent.com/14004106/120344404-c9c68880-c2b6-11eb-944a-386e33c9e52d.jpg)

It may be something that needs to be addressed upstream.

**Comment by SamWilsn** [comment]
https://github.com/ethereum/execution-apis
