### ISSUE TITLE
Proposal: add `eth_baseFeePerGas` method

### ISSUE THREAD

**Issue by fvictorio** [ethereum/execution-specs#207]
## Summary

Add a method, tentatively called `eth_baseFeePerGas`, to get the base fee of the next block.

## Motivation

The base fee of a block can be computed using some values from the previous block, like its base fee and the amount of gas used. The formula to do this isn't that involved so, in principle, clients could do it without the need to ask the node. But:

- While the formula is simple, it's not trivial. It also involves integer math that clients could get wrong.
- The formula involves some values like `ELASTICITY_MULTIPLIER` and `BASE_FEE_MAX_CHANGE_DENOMINATOR` that could change in the future (or even become dynamic values?)

## Specification

I'm not sure about the name of the method. `eth_baseFeePerGas` seems good enough, and consistent with existing methods, but it could be misleading. One alternative is `eth_nextBaseFeePerGas` or `eth_nextBlockBaseFeePerGas`.

I don't think this method should receive any params.

The return value would be just an `Integer`.

**Comment by fvictorio** [comment]
Update for this: this might still be included (maybe?), but this value can be obtained right now by doing this:

```js
const { baseFeePerGas } = await provider.send("eth_getBlockByNumber", ["pending", false])
```

**Comment by bford21** [comment]
> Update for this: this might still be included (maybe?), but this value can be obtained right now by doing this:
> 
> ```js
> const { baseFeePerGas } = await provider.send("eth_getBlockByNumber", ["pending", false])
> ```

Will this return a different value depending on the client?

**Comment by fvictorio** [comment]
> Will this return a different value depending on the client?

My guess is that it shouldn't, but I don't know if that's specified somewhere on this repo.
