### ISSUE TITLE
Proposal: New Repository and Process for JSON RPC Spec 

### ISSUE THREAD

**Issue by timbeiko** [ethereum/execution-specs#213]
The JSON RPC specification in this repository has different goals and requires different processes than the core protocol specification. I propose that we move it in a separate repository, similarly to how [eth2.0-specs](https://github.com/ethereum/eth2.0-specs/) and [eth2.0-apis](https://github.com/ethereum/eth2.0-apis) are structured. 

This repository would hence be only used to maintain the set of Core EIPs that each network upgrade consists of, the specification for devnets and potentially an executable version of the Yellowpaper/eth1 spec. 

Moving the JSON RPC spec to a separate repository would also allow us to have a better process to update the spec. As mentioned [here](https://github.com/ethereum/eth1.0-specs/pull/212#issuecomment-861128564) and [here](https://github.com/ethereum/eth1.0-specs/pull/212#issuecomment-861420062), we could move the JSON RPC spec to have branch-based releases.

**Comment by lightclient** [comment]
I'm a proponent of a separate repository for the `json-rpc` spec. 

A few potential names:
* `eth1.0-apis`
* `json-rpc-spec`
* `client-interface-specs`

Additionally, I'm happy to volunteer getting the repository setup and initially maintain it until we find a good rhythm for it.

**Comment by lightclient** [comment]
Per EIPIP meeting 35, we'll create an `eth1.0-apis` repo that will allow use to develop the spec. We'll fully remove the json-rpc from this repo after london.

**Comment by alcuadrado** [comment]
Thanks for your answers to [my comment](https://github.com/ethereum/eth1.0-specs/pull/212#issuecomment-861119955). 

I also think moving the spec into another repo, and having a branching-based processes as mentioned in the linked PR, makes sense.
