### ISSUE TITLE
Add support for t8n tests

### ISSUE THREAD

**Issue by lightclient** [ethereum/execution-specs#229]
A bit lower priority since we have access to all the `ethereum/tests` now.

**Comment by voith** [comment]
I'm working on this next.

**Comment by voith** [comment]
Update: I never got back to this. Please feel free to pick this one up if anyone is interested.

**Comment by SamWilsn** [comment]
@gurukamath I think this is safe to close now?

**Comment by gurukamath** [comment]
> @gurukamath I think this is safe to close now?

Yes. This was added in #756
