### ISSUE TITLE
Implement `*CALL` family

### ISSUE THREAD

**Issue by lightclient** [ethereum/execution-specs#230]
original issue: https://github.com/quilt/eth1.0-specs/issues/15

**Comment by voith** [comment]
I'm working on this. @lightclient Can you assign this to me?

**Comment by voith** [comment]
After reading the yellow paper, I've realized that this is far more involved than I thought it was and there's more functionality that needs to be implemented. 
List of things that need to be implemented before starting work on this(I'll be updating this list as I learn more):
- [ ] #263
