### ISSUE TITLE
Implement bloom filter and `LOGN` ops

### ISSUE THREAD

**Issue by lightclient** [ethereum/execution-specs#232]
^

**Comment by Bhargavasomu** [comment]
I'll be working on this post merging of #250 .

- [ ] LogN operations
- [ ] Logs Bloom

**Comment by Bhargavasomu** [comment]
This has been implemented. I'll leave this issue open as there are no test cases in place for these operations. I'll be integrating the tests once the remaining opcodes have been implemented.
