### ISSUE TITLE
More pull request templates

### ISSUE THREAD

**Issue by lightclient** [ethereum/execution-specs#245]
The current template makes sense for the pyspec, but we should have one that is more amenable to @timbeiko's work on eth1 coordination.

**Comment by SamWilsn** [comment]
What would we want to see?

**Comment by timbeiko** [comment]
FWIW, most changes I make are quite small, and the "template" that's most important is more the file template of things like [`london.md`](https://github.com/ethereum/eth1.0-specs/blob/master/network-upgrades/mainnet-upgrades/london.md), [`berlin.md`](https://github.com/ethereum/eth1.0-specs/blob/master/network-upgrades/mainnet-upgrades/berlin.md), etc.
