### ISSUE TITLE
Implement Block EVM opcodes

### ISSUE THREAD

**Issue by Bhargavasomu** [ethereum/execution-specs#266]
- [x] BLOCKHASH
- [x] COINBASE
- [x] TIMESTAMP
- [x] NUMBER
- [x] DIFFICULTY
- [x] GASLIMIT

**Comment by Bhargavasomu** [comment]
I'm working on this.

I have the changes ready in my local repo. I'll be opening a PR for this on Monday.

**Comment by Bhargavasomu** [comment]
Closing this as it has been implemented. I believe there is still some testing to be done on few opcodes belonging to this category. Leaving it open till the test cases are integrated.

**Comment by voith** [comment]
I have integrated all the test cases. @SamWilsn Please close this.
