### ISSUE TITLE
Increment evm.pc inside each opcode implementation, instead of in the interpreter loop

### ISSUE THREAD

**Issue by Bhargavasomu** [ethereum/execution-specs#278]
Put your thoughts out here.

**Comment by SamWilsn** [comment]
Most opcodes increment the program counter (`pc`) by one. The only exceptions are:

 - Jump Instructions (`jumpi`, `jump`)
 - Push Instructions (`push1`, `push2`, ...)

Before #273 the interpreter main loop [incremented `pc` after each instruction](https://github.com/ethereum/eth1.0-specs/blob/68d5d604743bb4d1659b1e1fedc405fcf04c07fa/src/ethereum/frontier/vm/interpreter.py#L96). After #273, the interpreter [conditionally increments](https://github.com/ethereum/eth1.0-specs/blob/7c82e7a02f10e1a789911acf6de8343a8dae17cc/src/ethereum/frontier/vm/interpreter.py#L104) `pc` based on a list of instructions.

I would prefer to see each opcode increment `pc` within its implementation function. So most opcodes (ex. `add`) would simply `evm.pc += 1`, but pushes can account for their length, and jumps can just set `pc` directly.

**Comment by lightclient** [comment]
Each instruction incrementing the `pc` themselves is fine with me.
