### ISSUE TITLE
What spellings should we use for the specification?

### ISSUE THREAD

**Issue by SamWilsn** [ethereum/execution-specs#282]
The spelling tool we're using for the Python and documentation is pretty limited, and it doesn't actually enforce a single consistent spelling (it allows `initialise` and `initialize`, for example.) I would like to see us improve the tool, and specifically add a feature for choosing a specific English spelling flavour.

I propose we use Canadian English spelling, since I'm Canadian, and would enjoy aggravating both our European and American contributors.

**Comment by lightclient** [comment]
@SamWilsn the RFC style guide accepts both American and British spelling, as long as it's consistent within the document. It gives the edge to American spelling for clusters of documents with different spellings (see [3.1](https://tools.ietf.org/id/draft-flanagan-7322bis-02.html#rfc.section.3.1) in the style guide). For that reason, I think we should go with the American spelling

**Comment by SamWilsn** [comment]
Fine, US spelling :rofl:
