### ISSUE TITLE
Implement chain sync

### ISSUE THREAD

**Issue by Bhargavasomu** [ethereum/execution-specs#322]
I'm working on the above.

The current idea is to use JSON RPC from Infura to download and store the blocks, but there is no rpc call to download multiple blocks. I'll be checking out `Batched JSON RPC` calls as suggested by @SamWilsn. This would also entail adding support to an external P2P service incase JSON RPC is slow.

**Comment by SamWilsn** [comment]
Should probably avoid embedding anything infura related by default, and just take a URL.

**Comment by voith** [comment]
I thought this project was about specs for the execution layer. I'm not sure how p2p is part of chain sync. 
@SamWilsn @Bhargavasomu Can either of you clarify?

**Comment by SamWilsn** [comment]
No p2p. We just want to be able to pull blocks from somewhere (like infura or a local client) and execute them.

**Comment by voith** [comment]
I see, Thanks for the explanation.

**Comment by ultratwo** [comment]
As discussed on the call I propose to implement as database backed state (see #330). This shouldn't clash with most of the chain sync work. Currently you can use the optimized state that stores stuff in memory and will probably run into current limitations of spec before you run out of memory.

If you decide to store blocks (which are not part of the state) in a database we should probably coordinate on which one (I think the main candidates are LevelDB and LMDB).

**Comment by SamWilsn** [comment]
https://github.com/ethereum/execution-specs/issues/234
