### ISSUE TITLE
`test_ethash.py` does not work on platforms other than Linux

### ISSUE THREAD

**Issue by ultratwo** [ethereum/execution-specs#329]
Currently the Ethash tests download and run the `geth-linux-amd64-1.10.8-26675454` build of geth. Obviously this only works on Linux, causing problems for Mac users such as @norswap.

Also it would be nice if we didn't download this file twice (once for `cpython`, once for `pypy`) every time the test suite is run.

**Comment by SamWilsn** [comment]
I pinged @Bhargavasomu about this yesterday. I think the correct solution is to just require `geth` be on the `PATH` and make it the user's responsibility.
