### ISSUE TITLE
Parent hash isn't validated

### ISSUE THREAD

**Issue by SamWilsn** [ethereum/execution-specs#387]
### Metadata

* **Hardfork**: frontier

### What was wrong?

The spec doesn't ensure that the `parent_hash` of the current block matches the hash of the previous block.

### Sources

> **parentHash**: The Keccak 256-bit hash of the parent block’s header, in its entirety; formally H<sub>p</sub>.

[source](https://ethereum.github.io/yellowpaper/paper.pdf#subsection.4.3)

**Comment by gurukamath** [comment]
Does this also mean additional test will have to be added, since the existing tests weren’t able to identify the issue? (I see all existing tests pass)

**Comment by SamWilsn** [comment]
@gurukamath adding a python test would be great!

**Comment by gurukamath** [comment]
@SamWilsn Added the relevant asserts to the state transition tests
