### ISSUE TITLE
Replace `uncle` with `ommer` in spec

### ISSUE THREAD

**Issue by lightclient** [ethereum/execution-specs#393]
`ommer` is the preferred terminology.

At the time of writing, these files use `uncle` instead of `ommer`:
 - https://github.com/ethereum/execution-specs/blob/8e8379de0d61b2b76265173108fabae7111e03bf/src/ethereum/frontier/spec.py#L58
 - https://github.com/ethereum/execution-specs/blob/8e8379de0d61b2b76265173108fabae7111e03bf/src/ethereum_spec_tools/sync.py#L312
 - https://github.com/ethereum/execution-specs/blob/8e8379de0d61b2b76265173108fabae7111e03bf/src/ethereum/frontier/trie.py#L52

**Comment by timbeiko** [comment]
Might be worth putting up an EthCatHerders bounty for this? cc: @poojaranjan

**Comment by poojaranjan** [comment]
To share with the ECH engineering team or put out a bounty, it will be helpful to get details of the task with link(s) where change is requested.

**Comment by SamWilsn** [comment]
Not sure if there were other locations, but I added a list of places inside the Python spec itself.

Think it's worth a bounty?

**Comment by lightclient** [comment]
Should take 10 minutes or less, not sure it's worth a bounty.

**Comment by gurukamath** [comment]
Does this method name change as well?

https://github.com/ethereum/execution-specs/blob/c5b6721123267e214e97f6c038ddbe7c60894866/src/ethereum_spec_tools/sync.py#L325
