### ISSUE TITLE
EIP-2681: Limit account nonce to 2^64-1 

### ISSUE THREAD

**Issue by axic** [ethereum/execution-specs#401]
[EIP-2681](https://eips.ethereum.org/EIPS/eip-2681) applies from genesis. It was properly merged into Geth this week and also the state tests repository has it merged.

**Comment by EmreKspToken** [comment]
EmreKspcoin

**Comment by EmreKspToken** [comment]
0xea3779dc2d94f40cdbc9cc953eb4f1a7a7538975

**Comment by gurukamath** [comment]
Which test cases would one use to build this? I am unable to find any JSON under tests that mentions this issue.

**Comment by SamWilsn** [comment]
> Which test cases would one use to build this? I am unable to find any JSON under tests that mentions this issue.

They can be found in the upstream repository: https://github.com/ethereum/tests/tree/develop/TransactionTests/ttNonce

The `fixtures` directory in [https://github.com/ethereum/execution-specs](execution-specs) is a submodule, and needs to be updated to get the latest tests.

**Comment by gurukamath** [comment]
@SamWilsn Thanks.

Also for the other change mentioned in [EIP-2681](https://eips.ethereum.org/EIPS/eip-2681)
"The CREATE and CREATE2 instructions to abort with an exceptional halt, where the account nonce is 2^64-1", I assume the relevant test is [High Nonce Test](https://github.com/ethereum/tests/blob/develop/GeneralStateTests/stCreateTest/CREATE_HighNonce.json).

However, I see that the structure of the above JSON is quite different from the fixtures have been tested so far for the VM System Operations (I looked at [suicide0](https://github.com/ethereum/tests/blob/82f6a5a7362e703a64dce303dd0c30f264b8195f/LegacyTests/Constantinople/VMTests/vmSystemOperations/suicide0.json) as a reference). For example, the "exec" key from the old JSON is missing in the new one (perhaps replaced by "transaction" based on a quick glance).

Is there any reference that could help me load the new format of tests? Or at least a dictionary that translates the old keys in JSON to the new one?

**Comment by lightclient** [comment]
@gurukamath what you are seeing is the difference between the "state" tests, "blockchain" tests, and "transaction" tests. The state tests are essentially a subset of blockchain tests and have been discontinued. The transaction tests validate the static aspects of rlp encoded transactions (more info [here](https://github.com/ethereum/go-ethereum/pull/23494)). There really isn't a concept of a "transaction test validator" yet in the execution spec, so you'd need to implement something. But it should be straightforward - it should decode the rlp to a transaction object and determine if any exceptions were raise (e.g. nonce too large) and if the tx valid, it verifies the hash and a few other components.

**Comment by gurukamath** [comment]
@lightclient Thanks for the link.
I have managed to implement the transaction test validator on my local feature branch to test that the transaction nonce is too large.

I am however, having trouble with the second point of [EIP-2681](https://eips.ethereum.org/EIPS/eip-2681) where I need to pass a transaction with high nonce through the VM and make sure that the CREATE instruction aborts with exceptional halt. I am trying to draw parallels between the already implemented vm system tests (for example [suicide0](https://github.com/ethereum/tests/blob/82f6a5a7362e703a64dce303dd0c30f264b8195f/LegacyTests/Constantinople/VMTests/vmSystemOperations/suicide0.json)) and [High Nonce](https://github.com/ethereum/tests/blob/develop/GeneralStateTests/stCreateTest/CREATE_HighNonce.json) but am having trouble mapping the two structures
