### ISSUE TITLE
Comprehensive exception reform

### ISSUE THREAD

**Issue by SamWilsn** [ethereum/execution-specs#437]
@ultratwo suggests that we do more comprehensive exception reform. There should be a superclasses called things like `FailWithAllGasError`, `InvalidTransactionError`, etc.. from which most other exceptions derive. That way we can avoid long `except:` lists.

_Originally posted by @ultratwo in https://github.com/ethereum/execution-specs/pull/423#discussion_r789669025_

**Comment by petertdavies** [comment]
I am now working on this.
