### ISSUE TITLE
Return an object from EVM execution instead of unwieldy tuples

### ISSUE THREAD

**Issue by petertdavies** [ethereum/execution-specs#439]
EVM execution currently returns unwieldy 5-6 element tuples in `interpreter.py`. These tuples should be turned into `dataclass`s or `NamedTuple`s to make code more readable.

Personally I would prefer `dataclass`s because we already use those in the spec.

**Comment by gurukamath** [comment]
@SamWilsn Is there anything pending on this issue? I believe we have implemented all the points.

**Comment by SamWilsn** [comment]
I think we're good! I just forget to close the issues :sweat_smile: 

If you add `(closes #...)` to your commit messages, it'll auto-close the issue when I merge.
