### ISSUE TITLE
Rename `src/*/vm/errors.py` to `src/*/vm/exceptions.py`

### ISSUE THREAD

**Issue by SamWilsn** [ethereum/execution-specs#479]
On the subject of "errors" vs "exceptions", I think it makes more sense to name `vm/errors.py` to `vm/exceptions.py` since I'm not convinced that things like `Revert` are actually errors.

_Originally posted by @petertdavies in https://github.com/ethereum/execution-specs/issues/470#issuecomment-1076540641_

**Comment by gurukamath** [comment]
Closed by #514
