### ISSUE TITLE
[Proposal] Add `pre-commit`

### ISSUE THREAD

**Issue by SauravMaheshkar** [ethereum/execution-specs#490]
I noticed that most of (if not all) the steps of the **[Development Section](https://github.com/ethereum/execution-specs#development)** can be automated via [pre-commit](https://pre-commit.com/) such as `isort`, `black`, `flake8`, `mypy` and `pytest`. Having [pre-commit](https://pre-commit.com/) would make that process much easier and enforce that the developers follow coding conventions. Although this would add `pre-commit` as a dependency for the project.

**Comment by SamWilsn** [comment]
I think we could dedicate a small section in the README about setting up pre-commit hooks, but in the end, that's a decision up to each contributor.
