### ISSUE TITLE
Openssl has disabled RIPEMD160 by default

### ISSUE THREAD

**Issue by petertdavies** [ethereum/execution-specs#506]
OpenSSL 3 has disabled various legacy hash functions by moving them to a legacy provider that isn't enabled by default. This includes RIPEMD160 which we use.

If you have OpenSSL 3 and try to use RIPEMD160 you will get `ValueError: [digital envelope routines] unsupported` or `ValueError: unsupported hash type ripemd160` under CPython and `Segmentation fault` under PyPy.

The issue can be resolved by adding this lines to `/etc/ssl/openssl.cnf`:

```
 [openssl_init]
 providers = provider_sect
 
 # List of providers to load
 [provider_sect]
 default = default_sect
+legacy = legacy_sect

 [default_sect]
 activate = 1

+[legacy_sect]
+activate = 1
```

**Comment by SamWilsn** [comment]
Interesting. Should we move this into the README?

**Comment by SamWilsn** [comment]
Looks like it might be possible to do it programmatically too: https://wiki.openssl.org/index.php/OpenSSL_3.0#Providers

**Comment by petertdavies** [comment]
I should be able to do that in pure python using the [CFFI](https://cffi.readthedocs.io/en/latest/index.html). I'll add it to my todo list.

**Comment by chfast** [comment]
Good to know. I plan to wrap OpenSSL into common API for Ethereum precompiles. Do you need to use any other cryptography libraries except OpenSSL?

**Comment by petertdavies** [comment]
> Good to know. I plan to wrap OpenSSL into common API for Ethereum precompiles. Do you need to use any other cryptography libraries except OpenSSL?

Actually, I think you need quite a few different crypto libraries.

* OpenSSL for `keccak256()`, `sha256()` and `ripemd160()`
* [libsecp256k1](https://github.com/bitcoin-core/secp256k1) for `secp256k1_recover()`
* A bignum library for `modexp`.
* A `bn_128` library for the `alt_bn_*` precompiles ([example](https://github.com/paritytech/bn))
* The Blake2 `F` compression function. If your language has C level performance this is probably easier to implement directly than add a dependency.

We use native python bignum support for `modexp` and implement `bn_128` and BLAKE `F` in python, but we have an unreasonable disregard for performance in the specs.

**Comment by chfast** [comment]
I'm attempting to "standardize" low-level API to wrap all Ethereum Precompiles implementation into single library. If this is something interesting to you I can make sure Python works from day one.

https://notes.ethereum.org/@ipsilon/abi_for_ethereum_precompiles_libraries

**Comment by q9f** [comment]
How much damage would it do to deprecate the ripemd160 builtin?

**Comment by q9f** [comment]
Ignore my previous thought experiment. Apparently, Ripemd160 was moved back to default providers.

https://www.openssl.org/blog/blog/2022/10/18/rmd160-and-the-legacy-provider

**Comment by q9f** [comment]
RIPEMD160 is back in default provider starting with version 3.0.7

**Comment by SamWilsn** [comment]
Sounds like there's nothing more for us to do here!
