### ISSUE TITLE
EIP-2929: Gas cost increases for state access opcodes

### ISSUE THREAD

**Issue by SamWilsn** [ethereum/execution-specs#522]
https://eips.ethereum.org/EIPS/eip-2929

**Comment by petertdavies** [comment]
I think this, along with #521 and #523, are a single package and would like to offer to implement all of them.

**Comment by gurukamath** [comment]
Closed in #554

**Comment by jsign** [comment]
@SamWilsn, @petertdavies, @gurukamath , may I ask something related to EIP-2929 implementation in the spec?

I'm looking at EIP-2929, in particular [this part](https://eips.ethereum.org/EIPS/eip-2929#parameters):
> In particular, if a scope reverts, the access lists should be in the state they were in before that scope was entered.

Looking at the execution-specs repo, I can't find the logic for that. IMO, should be [around here](https://github.com/ethereum/execution-specs/blob/master/src/ethereum/shanghai/vm/interpreter.py#L233-L235). 
From what I see, the `begin_transaction(env.state)` is only making a copy of the state (for a potential reversion, which is fine), but doesn't seem to include the access lists... so `rollback_transaction(...)` isn't indirectly doing that.

May be possible this behavior changed in a further EIP that I don't know, but from what I quickly checked in geth, I think they do this mentioned revert through their statedb-journal tracking as part of snapshoting.

(Note: if we confirm there's something actually missing, we can create another issue. But first I want to confirm if that's the case).

**Comment by gurukamath** [comment]
@jsign The access lists are updated in the parent evm, only when the child evm is successful. See [https://github.com/ethereum/execution-specs/blob/062fd94634c6fbd46d0d17ae2a41fae36e6090b9/src/ethereum/shanghai/vm/instructions/system.py#L319](here)

**Comment by jsign** [comment]
> @jsign The access lists are updated in the parent evm, only when the child evm is successful. See [here](https://github.com/ethereum/execution-specs/blob/062fd94634c6fbd46d0d17ae2a41fae36e6090b9/src/ethereum/shanghai/vm/instructions/system.py#L319)

Thanks for the reference!
