### ISSUE TITLE
Generating documentation takes too long

### ISSUE THREAD

**Issue by nam0mi** [ethereum/execution-specs#546]
This is how long it took to generate the doc on the server, is there any way to speed this time up?
```console
real	36m50.636s
user	35m45.408s
sys	0m46.352s
```

**Comment by SamWilsn** [comment]
The changes in #549 speed this up significantly, but I'd _really_ like to be able to use `-j auto` on the `sphinx-build` command line. Unfortunately, that's blocked until something like https://github.com/readthedocs/sphinx-autoapi/pull/332 gets merged.

**Comment by gurukamath** [comment]
> The changes in #549 speed this up significantly, but I'd _really_ like to be able to use `-j auto` on the `sphinx-build` command line. Unfortunately, that's blocked until something like [readthedocs/sphinx-autoapi#332](https://github.com/readthedocs/sphinx-autoapi/pull/332) gets merged.

I believe the time-consuming part of the build is the diff calculations. The `sphinx-build` parts take significantly less time. So, optimising the diff part should suffice in my opinion.
