### ISSUE TITLE
`modexp` doesn't correctly pad input values

### ISSUE THREAD

**Issue by SamWilsn** [ethereum/execution-specs#556]
### Metadata

* **Hardfork**: all of 'em

### What was wrong?

The modular exponentiation precompile doesn't pad its input value to the correct length before slicing it up, so each array access can `IndexError` incorrectly.

### Sources

https://github.com/ethereum/go-ethereum/blob/cb7f35996d8f8dfd44172b72cbb08829a33db527/core/vm/contracts.go#L365
https://github.com/ethereum/go-ethereum/blob/cb7f35996d8f8dfd44172b72cbb08829a33db527/core/vm/common.go#L54

**Comment by petertdavies** [comment]
How do you get the `IndexError`? Each access is of the form `right_pad_zero_bytes(data[x: x + length], length)`. Python slices are valid even if the bounds are entirely outside the list (e.g. `[1, 2, 3][100:1000] == []`).

**Comment by SamWilsn** [comment]
D'oh. That's what I get for switching languages so often. Please disregard.
