### ISSUE TITLE
Sender balance may not be checked when sending a value

### ISSUE THREAD

**Issue by SamWilsn** [ethereum/execution-specs#587]
### What was wrong?

> Hi, I've been reading the berlin execution specs in conjunction with the berlin yellow paper and noticed a discrepancy. The execution-specs only invalidate the block if the sender balance can cover the up-front gas_fee:
https://github.com/ethereum/execution-specs/blob/cc697f256d281476b9c9f810542e84fb78be2505/src/ethereum/berlin/spec.py#L599-L601 
However, in the YP (and client implementations), the tx.value is also added to the gas_fee for this check: https://github.com/ethereum/yellowpaper/blob/7251f10f25fc2a340c51c57e4a71970b525c0691/Paper.tex#L708-L711
>
> A check is done later as part of the EVM https://github.com/ethereum/execution-specs/blob/cc697f256d281476b9c9f810542e84fb78be2505/src/ethereum/berlin/vm/interpreter.py#L239-L243 which can raise an InsufficientFunds exception.
> However I believe this results in an exception which sets the gas to 0, which seems like a significant difference compared to the transaction being recognised as invalid earlier.
>
> Have I missed something here?

### Additional Context

[Reported by siladu on Discord](https://discord.com/channels/595666850260713488/856943705209569291/1008983249445474304).

**Comment by petertdavies** [comment]
siladu is correct that there is a bug here.

As it happens the `InsufficientFunds` exception doesn't get caught anywhere and so the process will terminate. However `InsufficientFunds` is not a subclass of `InvalidBlock` and isn't an acceptable way of marking a block invalid. The testsuite would correctly fail if an invalid block test existed for this case, but there doesn't seem to be one.

**Comment by SamWilsn** [comment]
> However `InsufficientFunds` is not a subclass of `InvalidBlock` and isn't an acceptable way of marking a block invalid.

This seems a bit odd. `CALL`, `CALLCODE`, `CREATE`, and `CREATE2` all check for sender balance and don't raise `InsufficientFunds` exceptions.

Is the correct play here to remove `InsufficientFunds` from the vm entirely?

**Comment by petertdavies** [comment]
> Is the correct play here to remove InsufficientFunds from the vm entirely?

Both the funds check and the stack depth check in `process_message()` are redundant and should go. All subclasses of `ExceptionalHalt` are cosmetic, I don't have any opinions on which ones should exist.

**Comment by SamWilsn** [comment]
> Both the funds check and the stack depth check in `process_message()` are redundant and should go.

I think both can be converted to debug `assert`s.



> All subclasses of `ExceptionalHalt` are cosmetic, I don't have any opinions on which ones should exist.

More specifically I was asking to double check my understanding that there isn't actually ever an exceptional halt (in the yellow paper sense) caused by insufficient funds: either the instruction fails but execution continues, or the transaction is invalid.

**Comment by SamWilsn** [comment]
Not a single test hits the test in Berlin: https://app.codecov.io/gh/ethereum/execution-specs/blob/master/src/ethereum/berlin/vm/interpreter.py

Time to set up test filling I guess :upside_down_face:

**Comment by gurukamath** [comment]
Perhaps the [Invalid Blocks Tests](https://github.com/ethereum/tests/tree/005931a700d4e4c4fd9e0d158771484403e7cb19/BlockchainTests/InvalidBlocks) need to have a group of tests for invalid transactions.

**Comment by SamWilsn** [comment]
I ended up writing a `BlockchainTests/ValidBlocks/bcStateTests` test that uses `expectException`. Do we not support those tests?

**Comment by gurukamath** [comment]
We do support [specific ones](https://github.com/ethereum/execution-specs/blob/cc697f256d281476b9c9f810542e84fb78be2505/tests/berlin/test_state_transition.py#L77). But these are the ones that are not expected to fail/except.

**Comment by chfast** [comment]
Can we have a state test for this case?

**Comment by SamWilsn** [comment]
> Can we have a state test for this case?

I have no idea, I'm basically just guessing with `retesteth` :sweat_smile: 

> Perhaps the [Invalid Blocks Tests](https://github.com/ethereum/tests/tree/005931a700d4e4c4fd9e0d158771484403e7cb19/BlockchainTests/InvalidBlocks) need to have a group of tests for invalid transactions.

No luck here either. The transaction doesn't make it into the block after RLP encoding. I'll try writing a pure Python test for it next.

**Comment by SamWilsn** [comment]
Looks like this isn't a bug per se. Instead of raising the exception at the beginning of the transaction, it was buried inside the vm. #600 moves things around to make it more clear.

**Comment by gurukamath** [comment]
I think there is a difference. Not implementing the check in the beginning results in an increment in the nonce and deduction of gas fees which is not reverted later. That does not happen if the check is implemented in the beginning.

**Comment by SamWilsn** [comment]
> I think there is a difference. Not implementing the check in the beginning results in an increment in the nonce and deduction of gas fees which is not reverted later. That does not happen if the check is implemented in the beginning.

You're right there is a difference, but the exception should bubble up (haven't actually tried.) Do/should we guarantee the `BlockChain` is in a valid state after trying to apply an invalid block?

**Comment by gurukamath** [comment]
>  Do/should we guarantee the `BlockChain` is in a valid state after trying to apply an invalid block?

Good question. Currently, we don't. [state check](https://github.com/ethereum/execution-specs/blob/bfe84c9a9b24695f160b4686d3b4640786ee9bac/tests/helpers/load_state_tests.py#L339)
