### ISSUE TITLE
The `frontier` -> `homestead` diff isn't correctly rendering `apply_fork`

### ISSUE THREAD

**Issue by SamWilsn** [ethereum/execution-specs#590]
The `apply_fork` function is different from [Frontier](https://ethereum.github.io/execution-specs/autoapi/ethereum/frontier/spec/index.html#apply-fork) to [Homestead](https://ethereum.github.io/execution-specs/autoapi/ethereum/homestead/spec/index.html#apply-fork). The [diff](https://ethereum.github.io/execution-specs/diffs/frontier_homestead/spec/index.html#apply-fork) doesn't show the change.

**Comment by gurukamath** [comment]
This is a curious one. Looks like we stopped highlighting this diff post [this PR](https://github.com/ethereum/execution-specs/commit/d49276f8fcdd785dcdac5ecda772e173efd63961#diff-df45e9a681bc629f3e184a783a6894c55925b1d80649e2b0547ffb278903848e) but I don't see anything in the PR that could account for this. I'll take a closer look.

**Comment by gurukamath** [comment]
The issue will likely no longer exist post #593

**Comment by gurukamath** [comment]
#593 has been superseded by #701. The issue will no longer exist post #701

**Comment by gurukamath** [comment]
#701 has been merged
