### ISSUE TITLE
Arbitrary File Write via Archive Extraction (Tar Slip)

### ISSUE THREAD

**Issue by bhaskarvilles** [ethereum/execution-specs#609]
Unsanitized input from a command line argument flows into extractall, where it is used to extract files from a tar archive. This may result files outside destination directory to be overwritten, resulting in an arbitrary file write.

https://github.com/ethereum/execution-specs/blob/5e8a9c33b4fa607cac58e1a92e186c1ef4f0230a/scripts/download_geth_linux.py#L31

### 10 steps in 1 file
`scripts/download_geth_linux.py`

16:12 `parser.parse_argsparser.parse_args` (SOURCE)
1 - 2 `parser.parse_args` (SOURCE)
1
`parser.parse_args`
2
`args`
3
`argsargs.dir`
4 - 5
`args`
4
`args.dir`
5
`dir: str`
6
`dir`
7
`dir`
8
`dirgeth_tar.extractall`
9 - 10
`dir`
9
`geth_tar.extractall`

**Comment by petertdavies** [comment]
The `geth_tar` file is trusted (indeed we execute the program it contains). The fact that `extract_all()` can misbehave on malformed tar files is irrelevant.
