### ISSUE TITLE
Implement `t8n` and `b11r` command line tools

### ISSUE THREAD

**Issue by petertdavies** [ethereum/execution-specs#625]
This would allow us to add support for EELS to to [goevmlab](https://github.com/holiman/goevmlab) and access the fuzzers there.

**Comment by SamWilsn** [comment]
Would this look like a CLI tool that takes a JSON filled test file as input?

**Comment by gurukamath** [comment]
SOme inconsistency in `t8n` needs to be sorted out. See [issue](https://github.com/ethereum/go-ethereum/issues/26861)
