### ISSUE TITLE
there is an error in Sepolia: Sepolia Timestamp 1677557088, maybe it's mainnet?

### ISSUE THREAD

**Issue by zrock23** [ethereum/execution-specs#719]
there is an error in Sepolia: Sepolia Timestamp 1677557088, maybe it's mainnet?
look this https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/shanghai.md !? 🎉🤗🥧

**Comment by timbeiko** [comment]
That timestamp converts from unix to Tuesday, February 28, 2023 4:04:48 AM UTC, which is the planned time of the Sepolia upgrade.

**Comment by q9f** [comment]
Interesting, did we move to timestamp-based upgrades?

**Comment by timbeiko** [comment]
We've moved to timestamps to ensure that upgrades are synchronized on the EL+CL. If we used a block number, we'd risk having slots where the update is activated on the CL but not EL due to missed slots.
