### ISSUE TITLE
Gas used in block incorrectly labeled `gas_remaining`

### ISSUE THREAD

**Issue by wschwab** [ethereum/execution-specs#720]
Hi!

Starting in the Frontier specification, the `apply_body` function in the specification (`spec.py`)  keeps track of how much gas remains until the block's gas limit is hit by referencing the block gas limit in a variable called `gas_available` ([here](https://github.com/ethereum/execution-specs/blob/master/src/ethereum/frontier/spec.py#L393)) and then subtracting the gas consumed by each transaction in a loop ([here](https://github.com/ethereum/execution-specs/blob/master/src/ethereum/frontier/spec.py#L422)). At the end of the processing, the final amount of gas consumed in the block is calculated by taking the full gas limit of the block and subtracting `gas_available` from it ([here](https://github.com/ethereum/execution-specs/blob/master/src/ethereum/frontier/spec.py#L438)). Here's the line:
```python
gas_remaining = block_gas_limit - gas_available
```
Just looking though the logic shows that this is not the gas _remaining_, but rather the gas _spent_. This isn't a bug - the Yellow Paper (page 5, second column in [this](https://ethereum.github.io/yellowpaper/paper.pdf) copy) states that `gasUsed` is the parameter that should be returned:

> gasUsed: A scalar value equal to the total gas used in transactions in this block; formally Hg.

This means the correct value is being returned, just that it is named something a bit misleading. A quick spot check of other forks makes it look like this naming convention persists across all forks.

I would recommend renaming `gas_available` to `gas_used` in accordance with the variable's name in the Yellow Paper.

It would seem that this issue is neither about an incorrect specification nor incorrect documentation - the specification is returning the correct value, and this is about a naming convention in the code, as opposed to docstrings or docs; as such, a blank issue was used.

I would happy to PR this if that would be more helpful.

Thanks!

**Comment by SamWilsn** [comment]
I believe you are correct. If you're willing to make the same doc/code changes repeatedly, we'd love a PR!

**Comment by SamWilsn** [comment]
Really appreciate the detailed write-up by the way <3

**Comment by wschwab** [comment]
PR opened: https://github.com/ethereum/execution-specs/pull/721
