### ISSUE TITLE
t8n tool errors

### ISSUE THREAD

**Issue by winsvega** [ethereum/execution-specs#773]
Here is the results of t8n execution on the state tests (skipping ConstantinopleFix as it is not declared in tool)

Fixed
 - [x] info: (GeneralStateTests/stCreate2/RevertInCreateInInitCreate2, fork: Berlin, TrInfo: d: 0, g: 0, v: 0, TrData: ` 0x305060..`) (empty contract collision)
- [x] info: (GeneralStateTests/stCreateTest/CreateTransactionHighNonce, fork: London, TrInfo: d: 0, g: 0, v: 0, TrData: ` 0x600160..`) (tr has nonce overflow the allowed value) 
- [x] info: (GeneralStateTests/stTransactionTest/HighGasPrice, fork: Berlin, TrInfo: d: 0, g: 0, v: 0, TrData: ` 0x..`) (tr has gaslimit x gasprice overflow)
- [x] info: (GeneralStateTests/stSStoreTest/InitCollision, fork: Berlin, TrInfo: d: 0, g: 0, v: 0, TrData: ` 0x600060..`) (empty account collision)
- [x] info: (GeneralStateTests/stRevertTest/RevertInCreateInInit, fork: Berlin, TrInfo: d: 0, g: 0, v: 0, TrData: ` 0x305060..`) (empty accounts?)
- [x] info: (GeneralStateTests/stExample/mergeTest, fork: Merge, TrInfo: d: 0, g: 0, v: 0, TrData: ` 0x00..`) (merge support?) 
- [x] info: (GeneralStateTests/stExample/invalidTr, fork: Berlin, TrInfo: d: 0, g: 0, v: 0, TrData: ` 0x..`) (intrinsic gas exception)
- [x] info: (GeneralStateTests/stEIP2930/addressOpcodes, fork: Berlin, TrInfo: d: 0, g: 0, v: 0, TrData: `:label valid 0x1a8451..`)
- [x] info: (GeneralStateTests/stEIP2930/coinbaseT01, fork: Berlin, TrInfo: d: 1, g: 0, v: 0, TrData: `:label T1baseInList 0x693c61..`)
- [x]  info: (GeneralStateTests/stEIP2930/coinbaseT2, fork: London, TrInfo: d: 0, g: 0, v: 0, TrData: `:label T2baseInList 0x693c61..`)
- [x] info: (GeneralStateTests/stEIP2930/transactionCosts, fork: Berlin, TrInfo: d: 1, g: 0, v: 0, TrData: `:label addrs_0_keys_0 0x00..`) 
- [x] info: (GeneralStateTests/stEIP2930/storageCosts, fork: Berlin, TrInfo: d: 0, g: 0, v: 0, TrData: `:label declaredKeyWrite 0x693c61..`) 
- [x] info: (GeneralStateTests/stEIP2930/manualCreate, fork: Berlin, TrInfo: d: 2, g: 0, v: 0, TrData: `:label allGood 0x5a3031..`) 
- [x] info: (GeneralStateTests/stEIP2930/variedContext, fork: Berlin, TrInfo: d: 0, g: 0, v: 0, TrData: `:label delegateCallerInAccessList 0x693c61..`)
- [x] info: (Shanghai/stEIP3860-limitmeterinitcode/creationTxInitCodeSizeLimit, fork: Shanghai, TrInfo: d: 1, g: 0, v: 0, TrData: `:label invalid 0x601080..`)
- [x] info: (GeneralStateTests/stSpecialTest/eoaEmpty, fork: London, TrInfo: d: 0, g: 0, v: 1, TrData: ` 0x693c61..`) 
- [x] info: (GeneralStateTests/stPreCompiledContracts/modexp, fork: Berlin, TrInfo: d: 28, g: 2, v: 0, TrData: ` 0x000000..`)  
- [x] info: (GeneralStateTests/stEIP1559/lowFeeCap, fork: London, TrInfo: d: 0, g: 0, v: 0, TrData: `:label declaredKeyWrite 0x00..`)
- [x] info: (GeneralStateTests/stEIP1559/lowGasLimit, fork: London, TrInfo: d: 0, g: 0, v: 0, TrData: ` 0x00..`)
- [x] info: (GeneralStateTests/stEIP1559/lowGasPriceOldTypes, fork: London, TrInfo: d: 0, g: 0, v: 0, TrData: ` 0x00..`) 
- [x] info: (GeneralStateTests/stEIP1559/outOfFunds, fork: London, TrInfo: d: 0, g: 0, v: 0, TrData: `:label declaredKeyWrite 0x00..`)
- [x] info: (GeneralStateTests/stEIP1559/outOfFundsOldTypes, fork: London, TrInfo: d: 0, g: 0, v: 0, TrData: ` 0x00..`)
- [x] info: (GeneralStateTests/stEIP1559/senderBalance, fork: London, TrInfo: d: 0, g: 0, v: 0, TrData: ` 0x..`)
- [x] info: (GeneralStateTests/stEIP1559/tipTooHigh, fork: London, TrInfo: d: 0, g: 0, v: 0, TrData: `:label declaredKeyWrite 0x00..`)
- [x] info: (GeneralStateTests/stEIP1559/transactionIntinsicBug, fork: London, TrInfo: d: 0, g: 0, v: 0, TrData: `:label declaredKeyWrite 0x00..`)
- [x] info: (GeneralStateTests/stEIP1559/valCausesOOF, fork: London, TrInfo: d: 0, g: 0, v: 0, TrData: ` 0x693c61..`) 
- [x] info: (GeneralStateTests/stRefundTest/refundFF, fork: Berlin, TrInfo: d: 0, g: 0, v: 0, TrData: ` 0x00..`)
- [x] info: (GeneralStateTests/stRefundTest/refundMax, fork: Berlin, TrInfo: d: 0, g: 0, v: 0, TrData: ` 0x00..`)
- [x] info: (GeneralStateTests/stRefundTest/refundSSTORE, fork: Berlin, TrInfo: d: 0, g: 0, v: 0, TrData: ` 0x00..`)
- [x] info: (GeneralStateTests/stEIP3607/transactionCollidingWithNonEmptyAccount_calls, fork: Berlin, TrInfo: d: 0, g: 0, v: 0, TrData: ` 0x..`)
- [x] info: (GeneralStateTests/stEIP3607/transactionCollidingWithNonEmptyAccount_callsItself, fork: London, TrInfo: d: 0, g: 0, v: 0, TrData: ` 0x..`)
- [x] info: (GeneralStateTests/stEIP3607/transactionCollidingWithNonEmptyAccount_init, fork: Berlin, TrInfo: d: 0, g: 0, v: 0, TrData: ` 0x00..`)
- [x] info: (GeneralStateTests/stEIP3607/transactionCollidingWithNonEmptyAccount_send, fork: London, TrInfo: d: 0, g: 0, v: 0, TrData: ` 0x..`)
- [x] info:  (GeneralStateTests/stMemoryTest/oog, fork: Merge, TrInfo: d: 28, g: 0, v: 0, TrData: `:label success 0x1a8451..`) 
- [x] info: (GeneralStateTests/stPreCompiledContracts/precompsEIP2929, fork: Shanghai, TrInfo: d: 342, g: 0, v: 0, TrData: `:label yes 0x1a8451..`) (statisticall python crash)
- [x] info: (GeneralStateTests/stEIP1559/intrinsic, fork: Merge, TrInfo: d: 15, g: 57, v: 0, TrData: ` 0x00ff..`)  (statisticall python crash)

```
--------
*** TOTAL ERRORS DETECTED: 8 errors during all test execution!
--------
info: (GeneralStateTests/stTransactionTest/ValueOverflow, fork: Berlin, TrInfo: d: 0, g: 0, v: 0, TrData: ` 0x..`)

info: (GeneralStateTests/stExample/accessListExample, fork: Berlin, TrInfo: d: 0, g: 0, v: 0, TrData: `:label declaredKeyWrite 0x00..`) (typed transaction before allowed fork)
info: (GeneralStateTests/stExample/basefeeExample, fork: Berlin, TrInfo: d: 0, g: 0, v: 0, TrData: `:label declaredKeyWrite 0x00..`) (typed transaction before allowed fork)
info: (GeneralStateTests/stExample/eip1559, fork: Berlin, TrInfo: d: 0, g: 0, v: 0, TrData: ` 0x00..`) (typed transaction before allowed fork)
info: (GeneralStateTests/stEIP1559/typeTwoBerlin, fork: Berlin, TrInfo: d: 0, g: 0, v: 0, TrData: `:label declaredKeyWrite 0x00..`)


```

**Comment by winsvega** [comment]
here is the first test that fails
```
retesteth -t GeneralStateTests/stCreate2 -- --singletest CREATE2_HighNonce --clients pyt8n
retesteth -t GeneralStateTests/stCreate2 -- --singletest CREATE2_HighNonce --clients pyt8n 
Running tests using path: /home/wins/Ethereum/tests
Running 1 test case...
Retesteth config path: /home/wins/.retesteth
Active client configurations: 'pyt8n '
Filter: 'CREATE2_HighNonce'
Running tests for config 'Python EVM StateTool' 2
Test Case "stCreate2": (1 of 1)
100%
Error: Post hash mismatch remote: 0x7b60effc750698e655c737e47ac46b110f58d555d29d96e87f4eaafaad501bff, expected: 0x0b9dc9e93eac0fc4dbcf79f6972506ab9638540aacc97c0525af5edaed385f71 (GeneralStateTests/stCreate2/CREATE2_HighNonce, fork: Constantinople, TrInfo: d: 0, g: 0, v: 0, TrData: ` 0x..`)
```

I get different post state hash than expected by the test. 
Here are the t8n tool inputs vs geth 
https://drive.google.com/file/d/17ypnqgg66YIvxaHWD26BktbfonRHJf0b/view?usp=drive_link

**Comment by winsvega** [comment]
WARNING:T8N:Transaction 0 failed: 
Error: Client reject transaction expected to be valid: (0xdbb728ec3bb0b37eb49274b839b556865bf27a654f91ef7787ef05e97d1fb15c) 
0xf884800a850a000000008080b630506000600e80602860003960006000f56002553d6000556020600060003e6000516001550000fe6211223360005260206000fd00001ca011b4e962eb5259b1eeb47b3aff0ce65c026d92b840511fecfbec1997ba4abb27a03970e23b1c2140165c823234ebeac740328c396bcee36ea61429a7995d721a70
Reason: Failed transaction:  (GeneralStateTests/stCreate2/RevertInCreateInInitCreate2, fork: Berlin, TrInfo: d: 0, g: 0, v: 0, TrData: ` 0x305060..`)

https://drive.google.com/file/d/1VGKDS1WkT9wlwtHiB-EAD8yWglx1XeO6/view?usp=drive_link

**Comment by gurukamath** [comment]
We had concluded that these test cases are not possible since they have zero `nonce` and `balance`, empty `code` but non-empty `storage`. We followed the discussion that happened some time ago on the `py-evm` repo. See [here](https://github.com/ethereum/py-evm/pull/1224)

We have ignored `stRevertTest/RevertInCreateInInit.json`, `stCreate2/RevertInCreateInInitCreate2.json` and `stSStoreTest/InitCollision.json` for the same reason. See [here](https://github.com/ethereum/execution-specs/blob/c90ccbee5eb1fd058c37e4fa8449b16e9ad217d1/tests/berlin/test_state_transition.py#L57).

**Comment by SamWilsn** [comment]
> it could have left over on the mainnet (even if its not the case)

We're of the opinion that if something hasn't happened on mainnet, we can create a "retroactive" EIP prohibiting the behaviour, in the same way that [EIP-2681](https://eips.ethereum.org/EIPS/eip-2681) retroactively limits account nonces.



> in Frontier this is totally possible

What would this look like?

**Comment by winsvega** [comment]
{ (CREATE 0 0 (lll { [[1]]1 } 0)) }

**Comment by petertdavies** [comment]
> If your evm fails on empty contract then ot will fail on this instruction on Frontier, so technically it will be a bug

We handle empty accounts in general fine. All of these test case relate to questions of what happens when you create a smart contract at an address which already has storage. The account must have no nonce and no code, otherwise the create would fail. This is only possible if you find an address collision (costing billions of dollars in compute) and deploy an empty contract there prior to Spurious Dragon. Whether this counts as an impossible situation is debatable.

Early in the development of the specs we followed `py-evm` precedent in refusing to implement the behaviour required to pass these tests and declaring the tests invalid. Once I have worked out what Geth's behaviour is we can decide if we should implement it.

**Comment by petertdavies** [comment]
I think I have figured it out.

According to the test suite, the semantics of `CREATE` and `CREATE2` when the target is an account with no nonce, no code, but some storage keys is as follows:

1. Delete the storage keys at the start of the `CREATE`.
2. For gas refund calculation purposes, treat the storage keys as having never existed.

We implement 1, but not 2. Due to architectural differences between us and production clients, it's not trivial for us to implement 2.

The problem is that `CREATE` deletes storage while bypassing the refund counter. If it `SSTORE` had deleted those keys, it would have given a bunch of refunds. When the new contract writes to the deleted keys the refund (which was never given) is removed turning the refund counter negative. We then crash because the refund counter is unexpectedly negative. Production clients (probably unknowingly) implement 2 to get around this problem.

**Comment by gurukamath** [comment]
@winsvega I looked at the remaining 38 tests in your list and they actually pass in our CI process. Let me outline the test that we perform in our CI process and do let me know if we are missing anything here.

1. We use the fixtures in the `BlockchainTests` folder to perform these tests. For example - `tests/fixtures/ethereum_tests/BlockchainTests/GeneralStateTests/stTransactionTest/HighGasPrice.json`
2. We then load the `env`, `alloc` and `txs` from the fixture for each block and perform the state transition using the `t8n` tool. We then use the output from the `t8n` tool and use the `b11r` tool to build a block out of it
3. Finally, we assert that the `rlp` of the block from the `b11r` tool exactly matches the `rlp` given in the fixture JSON.

Please let me know in case you see any issue with this testing approach.

**Comment by winsvega** [comment]
Ah this particular one must be coinbase touch. Its an issue only with state tests as it has 0 reward touch. So coinbase gets touched and an empty account created on pre EIP150. 

Since I assume the state transition is equivalent to the block sealing. Even with mining reward of 0. Or 0 tx (high nonce tx gets rejected)

But let me check the logs of pyt8n

**Comment by petertdavies** [comment]
I will make a PR to fix the issue I mentioned above. That should fix `stRevertTest/RevertInCreateInInit.json`, `stCreate2/RevertInCreateInInitCreate2.json` and `stSStoreTest/InitCollision.json`.

**Comment by gurukamath** [comment]
> `tests/fixtures/ethereum_tests/BlockchainTests/GeneralStateTests/stTransactionTest/HighGasPrice.json`
> 
> here is the thing. in blockchain test we can't check rejected transaction exceptions. I do export it in bc tests too but runners don't verify this. so when a tx get rejected in state tests -> blockchain test convertion. we get empty block. that means such test do nothing.

So u recommend using the `GeneralStateTests` instead of the `BlockChainTests` to run the evm tools tests?

**Comment by winsvega** [comment]
No, I am fixing those tests now.
But the situation seems to be state test only. Since we assume the state is rewarded 0 and despite transaction rejected, an empty transition is calculated.

So its a question about what should happen to empty coinbase when state reward set to 0 and 0 transactions provided in txs.(pre eip158)

And as for empty accounts, the t8n must support pre state with empty accounts having storage as on firrst networks it was possible to generate those

**Comment by gurukamath** [comment]
> And as for empty accounts, the t8n must support pre state with empty accounts having storage as on firrst networks it was possible to generate those

This should be handled post #794

**Comment by winsvega** [comment]
updated the errors. some errors still happen when unexpected type transaction is imported on prior forkrules. 
other errors I think occured due to unstability. the test has many vectors and sometimes when running 600 transactions over 5 fork rules in a raw, the tool just does not return outputs.

**Comment by gurukamath** [comment]
> updated the errors. some errors still happen when unexpected type transaction is imported on prior forkrules.
> other errors I think occured due to unstability. the test has many vectors and sometimes when running 600 transactions over 5 fork rules in a raw, the tool just does not return outputs.

I have checked the last remaining failing tests on the list and the following seems to be true.

`ValueOverflow` for multiple forks - I think there is some issue with the test fixture value. See [here](https://github.com/ethereum/tests/blob/0ec53d024c2b1f5175e70aba8f750cd4d37d9999/GeneralStateTests/stTransactionTest/ValueOverflow.json#L210)
`accessListExample`, `basefeeExample`, `eip1559`, `typeTwoBerlin` - These are just tests where the transaction type is not supported and the `t8n` tool is expected to throw an error when attempting to sign unsupported transactions. See [here](https://github.com/ethereum/go-ethereum/issues/26861#issuecomment-1464870686)
`intrinsic` for Merge and `precompsEIP2929` for Shanghai  - These tests pass on my end. Could you add more context to exactly what is incorrect here?

**Comment by winsvega** [comment]
1. yes this is experemental test providing a malicious rlp/ fields.  it crashed the t8n instead of it handling malicious input. 
 (in generated bc test I expect hive or client try to parse block rlp and handle the error. so client must not crash)
2. I expect transaction be rejected with the error message unsupported transaction type
3. this test just fails because pyt8n is unstable. (so it passes 99% of the time, but if you run many tests in raw some will start to fail, maybe also because run multithread)
