### ISSUE TITLE
CI doesn't recognise type hints in `eth2spec`

### ISSUE THREAD

**Issue by gurukamath** [ethereum/execution-specs#880]
The `eth2spec` library was added as a dependency in cancun since the `point_evaluation` precompile requires some of its functions. However, mypy fails on CI to recognise the type hints from this library even though the `py.typed` file was recently added to it. See [here](https://github.com/ethereum/consensus-specs/pull/3594). We will need to analyse and correct why this is not recognised on CI. As a temporary fix, a [type ignore](https://github.com/ethereum/execution-specs/blob/5e500d03e7798dcf3d989c688fc1bdebdf260929/src/ethereum/cancun/vm/precompiled_contracts/point_evaluation.py#L14) hint has been added. This will have to be removed once a permanent fix is applied.

Note: mypy did not throw any error upon local execution, so it could just be something specific to CI

**Comment by petertdavies** [comment]
Fixed by #885
