### ISSUE TITLE
Support copying 8192 blocks at EIP-2935 transition

### ISSUE THREAD

**Issue by petertdavies** [ethereum/execution-specs#949]
At the fork transition, EIP-2935 requires the last 8192 block hashes to be written to the history storage address. Since we only store the last 256 blocks we are unable to support this.

**Comment by SamWilsn** [comment]
Do you have an idea of how you want to solve this? I was thinking maybe modifying the preceding fork(s) to store more blocks?

**Comment by gurukamath** [comment]
> Do you have an idea of how you want to solve this? I was thinking maybe modifying the preceding fork(s) to store more blocks?

Based on the latest discussions on this EIP, I believe we won't need to refill the history window. We just let the ring buffer fill organically as the blocks are processed. Will keep an eye on this space.

**Comment by SamWilsn** [comment]
@gurukamath is this safe to close now?

**Comment by gurukamath** [comment]
> @gurukamath is this safe to close now?

Waiting for #963

**Comment by petertdavies** [comment]
Closed as back-filling has been removed from the spec.
