### ISSUE TITLE
Pyt8n missing module platformdirs

### ISSUE THREAD

**Issue by winsvega** [ethereum/execution-specs#969]
Please check that pip install command is correct 

I get this trace when trying to use t8n.

```
Traceback (most recent call last):
  File "/pyt8n/venv/bin/ethereum-spec-evm", line 5, in <module>
    from ethereum_spec_tools.evm_tools import main
  File "/pyt8n/src/ethereum_spec_tools/evm_tools/__init__.py", line 13, in <module>
    from .daemon import Daemon, daemon_arguments
  File "/pyt8n/src/ethereum_spec_tools/evm_tools/daemon.py", line 16, in <module>
    from platformdirs import user_runtime_dir
ModuleNotFoundError: No module named 'platformdirs'
```

**Comment by SamWilsn** [comment]
You'll need to add the feature `test` when installing the package.

If you already have it checked out locally, something like:

```bash
pip install -e .[test]
```

**Comment by winsvega** [comment]
Just `pip install .` won't do?

**Comment by SamWilsn** [comment]
The important part is the `[test]`. If you don't want an editable install, this'll work:

```
pip install .[test]
```

t8n and related tools are optional, and need additional dependencies to work.
