### ISSUE TITLE
Rendering has been broken for months

### ISSUE THREAD

**Issue by ritzdorf** [ethereum/execution-specs#980]
### What was wrong?

The rendered docs (https://ethereum.github.io/execution-specs/) have been broken for months.

Is there anyone working on this?

@SamWilsn is there something in docc that should be fixed? Even when fixing the TypeError here: https://github.com/ethereum/execution-specs/actions/runs/9993736756/job/27621818021#step:5:399 it does not seem to build properly.

I guess it would be good to know the status and if/where help is needed.

**Comment by SamWilsn** [comment]
Let me look into this. Thanks for raising!

**Comment by SamWilsn** [comment]
I believe this has been fixed with https://github.com/SamWilsn/docc/commit/5e86dfad8325bb4a5aaf7e9f2742dc220e8561b5

**Comment by SamWilsn** [comment]
We used to use [sphinx](https://www.sphinx-doc.org/en/master/), but reached some limitations in their plugin system.

We're in the very slow process of switching from reStructuredText to markdown, which is why you're seeing some weirdness.
