### ISSUE TITLE
Question about opcode `msize`

### ISSUE THREAD

**Issue by Alleysira** [ethereum/execution-specs#981]
### Metadata

* **Hardfork**: cancun

### What was wrong?

Hello developers,

I am testing various Ethereum virtual machines and have observed that when executing the opcode `0x59` (`MSIZE`), all the EVM implementations I tested (Geth, Besu, EthereumJS, Py-EVM) consistently return a value that is a multiple of 32 to the stack.

However, when I check the execution-spec at 

https://github.com/ethereum/execution-specs/blob/44ceab258abd42fdebdee06996bf0700b205ef98/src/ethereum/cancun/vm/instructions/memory.py#L122-L142

It seems that the specification directly pushes the length of `evm.memory` to the stack without accounting for the fact that the current memory size may not be a multiple of 32.

I noticed that when executing some opcodes that may cause memory expansion, this function will be called to make sure the length of memory to be multiple of 32. https://github.com/ethereum/execution-specs/blob/44ceab258abd42fdebdee06996bf0700b205ef98/src/ethereum/cancun/vm/gas.py#L154-L190

My question is **whether** the specification ensures that the length of memory will always be a multiple of 32, **or** if we need to add conditional checks or annotations to the `MSIZE` opcode to guarantee that it outputs a value that is a multiple of 32. Thank you for your attention.

#### evm.code

According to the definition of `msize`  at [evm.code](https://www.evm.codes/?fork=cancun), "The size is always a multiple of a word (32 bytes)."

#### yellow paper

I also check the shanghai version yellow book, in p36 it said: 

![image-20240727204640532](https://github.com/user-attachments/assets/d791ec1e-76a1-4378-a175-88426c85b4b3)

#### EVM implementation

I will give a bytecode example and its result after execution on different EVM implementations.

Bytecode as input : `631456015261af0b525960005260406000f3` 

```
PUSH4 0x14560152
PUSH2 0xaf0b
MSTORE 
MSIZE
PUSH1 0x40
PUSH1 0x00
RETURN
```

After execution, all EVMs returned with output `000000000000000000000000000000000000000000000000000000000000af400000000000000000000000000000000000000000000000000000000000000000`

where `0xaf40` is the result of opcode `msize` and  `0xaf40` is a multiple of 32.

The details are in the json files. 
[gethout.json](https://github.com/user-attachments/files/16400303/gethout.json), [besuout.json](https://github.com/user-attachments/files/16400299/besuout.json), [jsout.json](https://github.com/user-attachments/files/16400300/jsout.json), [pyout.json](https://github.com/user-attachments/files/16400301/pyout.json)

Thanks for your time.

**Comment by SamWilsn** [comment]
> I noticed that when executing some opcodes that may cause memory expansion, this function will be called to make sure the length of memory to be multiple of 32. 

Did you notice anywhere that expanded memory without using `calculate_gas_extend_memory`? I think we're pretty consistent in using it, but I've been wrong many times before :sweat_smile:

---

It might not be a bad idea to insert an `assert` into the MSIZE implementation (or maybe in the interpreter loop), to catch any bugs.
